### ISSUE TITLE
Remove "elementtree" and other unused dependencies.

### ISSUE THREAD

**Issue by infacto** [dpogue/seymour#28]
The package "elementtree" is unused, right? See `src/seymour.js`:

```js
var et = require('elementtree');
```
`et` is never read. And there is no more require of `elementtree`.

**Comment by dpogue** [comment]
I believe you are correct. We used to need to use `elementtree` directly for setting some preferences, but that's all handled by cordova-common now.

**Comment by dpogue** [comment]
We use `loud-rejection` to match what `cordova-cli` does. It could probably be replaced with some sort of event handler for uncaught rejections, but I'm a bit cautious of that because we had issues in the past with failures not including the errors message and having back stacktraces. It made debugging build failures extremely frustrating.
